---
title: "Exploring World Cup Statistics"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

<style type="text/css">

h1.title {
  text-align: center;
}

</style>

```{r setup, include=FALSE}
# Load packages
library(tidyverse)
library(viridis)
library(plotly)

# Set ggplot theme
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

```{r import df, include=FALSE, warning=FALSE, message=FALSE}
# Read in csv datafile
wc_df <- read_csv("data/12_4_dataset.csv") %>%
  janitor::clean_names() 
```

### Bivariable Explorations

<br>

```{r echo=FALSE, warning=FALSE, message=FALSE}
  plot_ly(
    data = wc_df,
    x = ~rank, 
    y = ~w,
    type = "scatter",
    mode = "markers",
    color = ~confederation, 
    text = ~country, 
    alpha = 0.7, 
    legendgroup = ~confederation,
    colors = viridis_pal(option = "D")(3)) %>% 
  layout(
    title = "2022 FIFA Ranking vs. Number of World Cup Games Won", 
    xaxis = list(title = "FIFA Ranking"), 
    yaxis = list(title = "Games Won"))
```

<br>

```{r echo=FALSE, warning=FALSE, message=FALSE}
  plot_ly(
    data = wc_df,
    x = ~pld, 
    y = ~w,
    type = "scatter",
    mode = "markers",
    color = ~confederation, 
    text = ~country, 
    alpha = 0.7, 
    legendgroup = ~confederation,
    colors = viridis_pal(option = "D")(3)) %>% 
  layout(
    title = "Number of Games Played vs. Number of World Cup Games Won in the World Cup", 
    xaxis = list(title = "Games Played"), 
    yaxis = list(title = "Games Won"))
```

<br>

```{r echo=FALSE, warning=FALSE, message=FALSE}
  plot_ly(
    data = wc_df,
    x = ~gf, 
    y = ~w,
    type = "scatter",
    mode = "markers",
    color = ~confederation, 
    text = ~country, 
    alpha = 0.7, 
    legendgroup = ~confederation,
    colors = viridis_pal(option = "D")(3)) %>% 
  layout(
    title = "Number of Goals For vs. Number of World Cup Games Won in the World Cup", 
    xaxis = list(title = "Goals For"), 
    yaxis = list(title = "Games Won"))
```

<br>

```{r echo=FALSE, warning=FALSE, message=FALSE}
  plot_ly(
    data = wc_df,
    x = ~ga, 
    y = ~w,
    type = "scatter",
    mode = "markers",
    color = ~confederation, 
    text = ~country, 
    alpha = 0.7, 
    legendgroup = ~confederation,
    colors = viridis_pal(option = "D")(3)) %>% 
  layout(
    title = "Number of Goals Against vs. Number of World Cup Games Won in the World Cup", 
    xaxis = list(title = "Goals Against"), 
    yaxis = list(title = "Games Won"))
```

<br>

```{r echo=FALSE, warning=FALSE, message=FALSE}
  plot_ly(
    data = wc_df,
    x = ~d, 
    y = ~w,
    type = "scatter",
    mode = "markers",
    color = ~confederation, 
    text = ~country, 
    alpha = 0.7, 
    legendgroup = ~confederation,
    colors = viridis_pal(option = "D")(3)) %>% 
  layout(
    title = "Number of Games Drawn vs. Number of World Cup Games Won in the World Cup", 
    xaxis = list(title = "Number of Draws"), 
    yaxis = list(title = "Games Won"))
```
