---
title: "Model Building"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

# Overview

##### We summarize the statistics of world cups from 1990 to 2018 for all the countries that made to the World Cup.
##### We tried different ways for model selection, inclusing step-wise selection, foward and backward selection, and LASSO, with different selecting criterias, such as AIC, BIC, and p-values. After comparing the rmse, R-square and p-values, we decide to use the model from foward selection. Our final model is  w = -1.554369 + 0.661219pld - 0.622216d + 0.015920rank + 0.153794gf -0.225378ga.

# Potential predictors

#### VARIABLES AND DEFINITIONS
country: Individual country (represents national soccer team)
part: Number of times each country has participated in the World Cup (all time)
pld: Number of games played in the World Cup (since 1990)
w: Number of soccer games a country has won in the World Cup (since 1990)
d: Number of soccer games a country has drawn in the World Cup (since 1990)
l: Number of soccer games a country has lost in the World Cup (since 1990)
gf: Number of goals a country has scored against opponents in the World Cup (since 1990)
ga: Number of goals scored against a country in the World Cup (since 1990)
gd: Goal difference of country (goals scored by country minus goals scored against country)
pts: Number of points accumulated by country in the World Cup (since 1990)
rank: Country Official FIFA ranking (2022 Rankings)
player: Name of top record goal scorer
goals: Number of goals scored by top record goal scorer
land_area_km: Total area of the land-based  portions of a country’s geography (measured in square kilometers, km²)
confederation: Country FIFA confederation 




